#!/usr/bin/with-contenv bash

WEB_PORT=${WEB_PORT:-18080}
WEBUI_PORT=${WEBUI_PORT:-8080}

if [[ ! -e /config/caddy/Caddyfile ]];
then
  mkdir -p /config/caddy
  cat > /config/caddy/Caddyfile << EOF
{
  admin off
  auto_https off
}

(rules) {
  @mobile_api {
    header User-Agent *Mobile*
    path /api/*
  }
  @mobile_ui {
    header User-Agent *Mobile*
    path *
  }
  @pc {
    not header User-Agent *Mobile*
  }
}

http://:${WEB_PORT} {
  import rules
  reverse_proxy @pc http://127.0.0.1:${WEBUI_PORT} {
    header_up Host 127.0.0.1:${WEBUI_PORT}
    header_up Origin http://127.0.0.1:${WEBUI_PORT}
    header_up Referer http://127.0.0.1:${WEBUI_PORT}
  }
  reverse_proxy @mobile_api http://127.0.0.1:${WEBUI_PORT} {
    header_up Host 127.0.0.1:${WEBUI_PORT}
    header_up Origin http://127.0.0.1:${WEBUI_PORT}
    header_up Referer http://127.0.0.1:${WEBUI_PORT}
  }
  file_server @mobile_ui {
    root /vuetorrent
  }
}
EOF
fi

exec s6-setuidgid root /caddy run --config /config/caddy/Caddyfile
