#!/usr/bin/env bash

OPENWRT_VERSION=$1

DPKG_ARCH=$(dpkg-architecture -q DEB_BUILD_ARCH)
RPI_BOARD='bcm2709'
RPI_VERSION='2'

if [ "$DPKG_ARCH" = 'arm64' ];
then
  RPI_BOARD='bcm2711'
  RPI_VERSION='4'
fi

echo https://downloads.openwrt.org/releases/${OPENWRT_VERSION}/targets/bcm27xx/${RPI_BOARD}/openwrt-${OPENWRT_VERSION}-bcm27xx-${RPI_BOARD}-rpi-${RPI_VERSION}-squashfs-factory.img.gz
