#!/bin/sh

if [ -f /dev/k3s ];
then
  mount /dev/k3s /host
  mkdir -p /host/etc/rancher
  mkdir -p /host/var/lib/rancher/k3s
  mkdir -p /host/var/lib/kubelet
  mkdir -p /host/var/lib/cni
  mkdir -p /host/var/log
  mount -o bind /host/etc/rancher          /etc/rancher
  mount -o bind /host/var/lib/rancher/k3s  /var/lib/rancher/k3s
  mount -o bind /host/var/lib/kubelet      /var/lib/kubelet
  mount -o bind /host/var/lib/cni          /var/lib/cni
  mount -o bind /host/var/log              /var/log
fi

exec /bin/k3s $@
