#!/bin/bash

export HOME=/root
export TERM=xterm
export PATH=/usr/local/bin:/usr/bin:/bin:/sbin:/usr/local/sbin:/usr/sbin

mkdir /dev/pts
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devpts devpts /dev/pts
mount -o rw,remount /

mount -t tmpfs tmpfs /tmp -o rw,nosuid,nodev
mount -t tmpfs tmpfs /var/run -o rw,nosuid,nodev
mount -t tmpfs tmpfs /var/log -o rw,nosuid,nodev
mount -o bind /usr/lib/uml/modules /lib/modules

hostname uml
ip link set dev lo up
ip link set dev vec0 up

for item in $(cat /proc/cmdline);
do
  key=$(echo "$item" | awk -F '=' '{print $1}')
  value=$(echo "$item" | awk -F '=' '{print $2}')
  if [ "$key" = "cidr" ];
  then
    ip addr add $value dev vec0
  fi
  if [ "$key" = "gateway" ];
  then
    route add default gw $value
  fi
done

ip addr add 192.168.123.123/24 dev vec0

screen -d -m socat TCP-LISTEN:12345,fork,reuseaddr EXEC:/bin/bash
exec /usr/bin/tini /bin/sleep infinity
