#!/usr/bin/env bash

VERSION=$1
FRP_ARCH='linux_'
DEB_ARCH=$(dpkg-architecture -q DEB_BUILD_ARCH)
RELEASE_URL=https://api.github.com/repos/fatedier/frp/releases/tags/v$VERSION
USER_AGENT='Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36'

case $DEB_ARCH in
  amd64)
    FRP_ARCH=$FRP_ARCH'amd64'
    ;;
  arm64)
    FRP_ARCH=$FRP_ARCH'arm64'
    ;;
  *)
    FRP_ARCH=$FRP_ARCH'arm'
    ;;
esac

FILE="frp_${VERSION}_${FRP_ARCH}"
DOWNLOAD_URL="$(curl -fsSL -H "user-agent: $USER_AGENT" "$RELEASE_URL" | jq -r '.assets[].browser_download_url' | grep "$FRP_ARCH.tar.gz")"
echo "[FRP][DOWN] $DOWNLOAD_URL"

curl -L "$DOWNLOAD_URL" --output $FILE.tgz
tar -xvf $FILE.tgz
mv $FILE /frp
