#!/bin/bash

exists_group=$(getent group $PGID 2>/dev/null | awk -F ':' '{print $1}')
exists_user=$(id -nu $PUID 2>/dev/null)

if [ "$exists_group" != "www-data" ];
then
  [ "$exists_group" != "" ] && groupmod -g 10086 $exists_group
  groupmod -g $PGID www-data
fi

if [ "$exists_user" != "www-data" ];
then
  [ "$exists_user" != "" ] && usermod -u 10086 $exists_user
  usermod -u $PUID www-data
  chown -R www-data:root /var/www/owncloud
fi

/usr/bin/entrypoint /usr/bin/owncloud server
