#!/bin/bash

if [ ! -f /etc/synoinfo.conf ];
then
  rand=$(cat /proc/sys/kernel/random/uuid | awk -F '-' '{print $1}')
  echo "unique=\"synology_${rand}_720+\"" > /etc/synoinfo.conf
fi

rm /.dockerenv

/var/packages/pan-xunlei-com/xunlei_cgi
