#!/bin/bash

if [ ! -f /rootfs/etc/synoinfo.conf ];
then
  rand=$(cat /proc/sys/kernel/random/uuid | awk -F '-' '{print $1}')
  echo "unique=\"synology_${rand}_720+\"" > /rootfs/etc/synoinfo.conf
fi
echo '{"port":5050, "internal": false, "dir":"/downloads"}' > /rootfs/var/packages/pan-xunlei-com/config.json && \

proot \
  -b /dev \
  -b /run \
  -b /tmp \
  -b /sys \
  -r /rootfs \
  --kill-on-exit \
  -b /downloads:/downloads \
  -b /etc/hosts:/etc/hosts \
  -b /etc/hostname:/etc/hostname \
  -b /etc/resolv.conf:/etc/resolv.conf \
  /var/packages/pan-xunlei-com/xunlei_cgi
