#!/bin/sh

chmod 777 /dev/dri/*

groupmod -g $PGID users
usermod -u $PUID dosk
chown -R $PUID:$PGID /config
chown -R $PUID:$PGID /cache

/usr/sbin/gosu $PUID:$PGID /jellyfin/jellyfin \
  --datadir /config \
  --cachedir /cache \
  --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg
