#!/usr/bin/env bash

# only amd64
DEB_ARCH=$(dpkg-architecture -q DEB_BUILD_ARCH)
if [ "$DEB_ARCH" != "amd64" ];
then
  exit 0;
fi

# workdir
mkdir -p /work
chmod 777 /work
cd /work

# intel driver
curl -fsSL "$1" --output /work/intel.deb
apt install -y ./intel.deb

# ffmpeg
curl -fsSL "$2" --output /work/ffmpeg.deb
apt install -y ./ffmpeg.deb

# ffmpeg permission hack
mv /usr/lib/jellyfin-ffmpeg/ffmpeg /usr/lib/jellyfin-ffmpeg/ffmpeg.exe
gcc /usr/lib/jellyfin-ffmpeg/ffmpeg.c -o /usr/lib/jellyfin-ffmpeg/ffmpeg
chmod u+s /usr/lib/jellyfin-ffmpeg/ffmpeg

# cleanup
cd /
rm -rvf /work
rm /usr/lib/jellyfin-ffmpeg/ffmpeg.c
