#!/bin/bash

# change password
/install/vncpwd/vncpwd ~/.vnc/passwd set $PASSWORD

# start vnc
touch $XAUTHORITY
rm -rvf /tmp/.X*
/usr/bin/vncserver $DISPLAY -geometry $GEOMETRY -depth 24
websockify -D --web=/usr/share/novnc 5070 localhost:5900

# run i3wm
export XKL_XMODMAP_DISABLE=1
/usr/bin/autocutsel -s CLIPBOARD -fork
/usr/bin/i3 &
/usr/bin/firefox
