#!/bin/bash

URL="$1"
PERMANENT=''
HW=''
case "$(dpkg-architecture -q DEB_BUILD_ARCH)" in
  amd64)
    URL=${URL/ARCH/x86_64}
    PERMANENT='OD'
    HW='DS3617xs'
    ;;
  arm64)
    URL=${URL/ARCH/armv8}
    PERMANENT='QK'
    HW='DS119j'
    ;;
  *)
    ;;
esac
curl "$URL" --output owapp.spk

tar -xvf owapp.spk
tar -xvf package.tgz
mv owapp /root/owapp
sed -i 's/proc\/sys\/kernel/root/g' /root/owapp/bin/owapp_monitor
echo '<html><head><meta http-equiv="refresh" content="0;url=/owdl/index.html"></head></html>' > /root/owapp/index.html

echo "HW=${HW}" > /root/env
echo "PERMANENT=${PERMANENT}" >> /root/env
