#!/bin/bash

source /root/env

if [ ! -f /root/syno_hw_version ];
then
  echo $HW > /root/syno_hw_version
fi

if [ ! -f /root/syno_mac_address1 ];
then
  ip link show eth0 | grep ether | awk '{print $2}' | xargs > /root/syno_mac_address1
fi

if [ ! -f /root/syno_serial ];
then
  echo "$(openssl rand -hex 1 | tr [a-z] [A-Z])${PERMANENT}N$(openssl rand -hex 3 | tr [a-z] [A-Z])" > /root/syno_serial
fi

sh /root/owapp/bin/owapp_monitor
