#!/bin/bash

cat > /ss_config.json << EOF
{
  "server":"$SERVER_ADDR",
  "server_port":$SERVER_PORT,
  "local_address": "127.0.0.1",
  "local_port":1080,
  "password":"$PASSWORD",
  "timeout":$TIMEOUT,
  "method":"$METHOD",
  "fast_open": $FASTOPEN
}
EOF

/usr/local/bin/ssserver -c /ss_config.json
